import "@/styles/reset.css"
import { Providers } from "./provider";
import NavBar from "@/components/NavBar";
import theme from "@/theme/theme";

export const metadata = {
  title: "Portafolio || LNSolutions",
  description: "Generated by Next.js",
  name: "viewport",
  content: "width=device-width, initial-scale=1",
};
//Navegacion principal del sitio web
export default function RootLayout({ children }) {
  const bodyStyle = {
    backgroundColor: `${theme.colors.secondary}`
  }

  return (
    <html lang="es">
      <body style={bodyStyle}>
        <Providers>
          <NavBar />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}

